/tracking/verbose 1
#/gesim/phys/SelectPhysics QGSP_BIC_HP


/gesim/detector/selectDetector 3 #for GeIII
/gesim/analysis/selectDetector 3 #for GeIII
/gesim/source/setSourcePosition LZAmBe2inOuterWCapsuleEndcap #source geometry name: LZAmBe2Remote for AmBe without outer tungsten capsule in remote position, LZAmBe2inOuterWCapsuleRemote for AmBe in outer tungsten capsule in remote position, LZAmBe2inOuterWCapsuleEndcap for AmBe in outer tungsten capsule on endcap

#uncomment the following 4 lines to get visualization files (.wrl); comment if you need to simulate a large amount of particles, e.g. > 1000
#/vis/open VRML2FILE
#/vis/drawVolume
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate

/run/initialize
/grdm/analogueMC 1
/grdm/verbose 1
/grdm/allVolumes


/process/em/fluo true
/process/em/auger true


/histo/fileName /mnt/raid5/users/amslivar/AmBe_work/AmBe_v2/GeSimROOTfiles/AmBe_n012_gammas_1mievts # output root file name
#BEGIN seed
/random/setSeeds 9097
#END seed


/run/beamOn 1000000

